# Generated by Django 4.0.5 on 2022-08-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_reviewmessage_user'),
        ('notification', '0002_notification_is_deleted_notification_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.review'),
        ),
    ]
