# Generated by Django 4.0.5 on 2022-08-11 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_property_balconies_alter_property_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstar',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.property'),
            preserve_default=False,
        ),
    ]
