# Generated by Django 4.0.5 on 2022-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_totalstar_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalstar',
            name='totalStar',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
