# Generated by Django 4.0.5 on 2022-08-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_totalstar_totalstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent'), ('PG', 'PG')], default='Rent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_out_to',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('Family', 'Family'), ('Men', 'Men'), ('Girls', 'Girls')], max_length=50, null=True),
        ),
    ]
