# Generated by Django 4.0.5 on 2022-08-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_property_category_alter_property_rent_out_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lease_duration',
            field=models.CharField(choices=[('1 month', '1 month'), ('6 month', '6 month'), ('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year')], max_length=20, null=True),
        ),
    ]
