# Generated by Django 4.0.5 on 2022-08-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_property_lease_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rentedStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell'), ('PG', 'PG')], default='Rent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
