# Generated by Django 4.0.5 on 2022-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_reviewmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmessage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmessage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
