# Generated by Django 4.0.5 on 2022-08-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_reviewmessage_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_out_to',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('Family', 'Family'), ('Men', 'Men'), ('Girls', 'Girls')], default='Any', max_length=50, null=True),
        ),
    ]
