# Generated by Django 4.0.5 on 2022-08-16 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_property_rent_out_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_out_to',
            field=models.CharField(choices=[('Any', 'Any'), ('Family', 'Family'), ('Men', 'Men'), ('Girls', 'Girls')], default='Any', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RentedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
