# Generated by Django 4.0.5 on 2022-08-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_payingguestproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='payingGuestStatus',
            field=models.BooleanField(default=False),
        ),
    ]
