# Generated by Django 4.0.5 on 2022-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_property_payinggueststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='deleted_from_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewmessage',
            name='deleted_from_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewmessage',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
