# Generated by Django 4.0.5 on 2022-08-18 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_review_deleted_from_notification_review_is_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
